### ISSUE TITLE
Fatal Python error: PyThreadState_Get: no current thread Abort trap: 6

### ISSUE THREAD

**Issue by fateh3** [xethru/XeThru_ModuleConnector_Examples#1]
Trying to run python file  **xep_distance_demo_host.py**, 

When i run this file i get above error, Pythread, How can i resolve it. 

Thanks , 

Ramneek

**Comment by charlieshao5189** [comment]
The cause for this problem varies if you search this error on google. I would suggest you clean up different python versions in you computer and reinstall python37.

**Comment by fateh3** [comment]
did you guys found what this error is for ?

**Comment by charlieshao5189** [comment]
Not really, did not get report for other users by far. 
This seems to be a fixed bug:
https://stackoverflow.com/questions/19531969/segmentation-fault-11-in-os-x

**Comment by fateh3** [comment]
ImportError: dynamic module does not define module export function (PyInit__moduleconnectorwrapper)

this pymoduleconnector is for 3.6 and 2.7 right ?
i am getting this error while i make run a file. Not able to find how to solve.

Hardware - ubuntu 16.04

**Comment by charlieshao5189** [comment]
The latest is ModuleConnector-unix-1.6.2. It provides libraries installation for python 3.5 and python 2.7. Which version of library you have installed? Could you post the whole printout when you run the example script?
