### ISSUE TITLE
MATLAB disp_x4_settings.m status 1 error

### ISSUE THREAD

**Issue by cjosephson** [xethru/XeThru_ModuleConnector_Examples#2]
I have an ~~X4M04~~ X4M03 and when I try to use disp_x4_settings.m as called in some of the examples, I get errors like this: 

```
Error using ModuleConnector.RadarInterface/xep_x4driver_get_tx_center_frequency (line 381)
Call returns status=1

Error in ModuleConnector.XEP/x4driver_get_tx_center_frequency (line 209)
status = this.radarInterface.xep_x4driver_get_tx_center_frequency(this.x2_instance, itPtr );​
```

I am running on linux.

**Comment by charlieshao5189** [comment]
I think there is no X4M04 module from XeThru, but anyway, this should be able to be fixed by uploading the latest firmware. You can connect XeThru module to the latest XeThru Explore to upload new firmware.

**Comment by cjosephson** [comment]
I am using Explorer 2.7.3 and I don't see any option to update firmware:
![screen shot 2019-02-27 at 3 13 03 pm](https://user-images.githubusercontent.com/707398/53529673-346a3780-3aa2-11e9-89e5-bc50e2fbbc61.png)

**Comment by charlieshao5189** [comment]
Added OpenBootloader is added from 3.3.0. You need to use Atmel-ICE to program the firmware in this condition.

**Comment by charlieshao5189** [comment]
OpenBootloader is added from V3.3.0. Need to use Atmel-ICE to program the firmware release after V3.3.0 in this condition.
